resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/concourse-arm

  - name: builder-image
    type: registry-image
    source: 
      repository: cirocosta/builder


  - name: builder-image-arm64
    tags: [arm]
    type: registry-image-arm
    source:
      repository: cirocosta/builder-task
      tag: arm64

 
jobs:
  - name: build
    public: true
    plan:
      - in_parallel:
        - get: repository
          trigger: true
        - get: builder-image
          trigger: true
        - get: builder-image-arm64
          tags: [arm]
          trigger: true

      - in_parallel:
          fail_fast: true
          steps:
          - task: build-binaries
            image: builder-image
            privileged: true
            params: { TARGET: binaries }
            output_mapping: { image: image_binaries }
            file: repository/ci/tasks/build-image.yml

          - task: build-registry-image-resource
            tags: [arm]
            image: builder-image-arm64
            privileged: true
            params: { TARGET: registry-image-resource, BUILD_ARG_arch: native }
            output_mapping: { image: image_registry-image-resource }
            file: repository/ci/tasks/build-image.yml

      - task: produce-rc
        image: image_binaries
        config:
          platform: linux
          inputs: [{name: image_registry-image-resource}]
          run:
            path: /bin/sh
            args:
              - -ce
              - |
                find .
