jobs:
  - name: builder
    serial: true
    public: true
    plan:
      - in_parallel:
        - {get: repository, trigger: true}
        - {get: builder-task-image-arm64, tags: [arm]}

      - in_parallel:
          fail_fast: true
          steps:
            - task: build-arm64
              file: repository/ci/tasks/build-image.yml
              image: builder-task-image-arm64
              output_mapping: {image: image-arm64}
              params: { TARGET: builder-task-image, PLATFORM: arm64, BUILD_ARG_arch: native }
              privileged: true
              tags: [arm]

            - task: build-arm
              file: repository/ci/tasks/build-image.yml
              image: builder-task-image-arm64
              output_mapping: {image: image-arm}
              params: { TARGET: builder-task-image, PLATFORM: arm, BUILD_ARG_arch: native }
              privileged: true
              tags: [arm]

      - in_parallel:
          fail_fast: true
            - put: builder-task-image-arm64
              get_params: {format: oci}
              inputs: [image-arm64]
              params: {image: image-arm64/image.tar}
              tags: [arm]

            - put: builder-task-image-arm
              get_params: {format: oci}
              inputs: [image-arm]
              params: {image: image-arm/image.tar}
              tags: [arm]


  - name: registry-image-resource
    serial: true
    public: true
    plan:
      - in_parallel:
        - {get: repository, trigger: true}
        - {get: builder-task-image-arm64, tags: [arm]}

      - in_parallel:
          fail_fast: true
          steps:
            - task: build-arm64
              tags: [arm]
              image: builder-task-image-arm64
              privileged: true
              output_mapping: {image: image-arm64}
              params: { TARGET: registry-image-resource, PLATFORM: arm64, BUILD_ARG_arch: native }
              file: repository/ci/tasks/build-image.yml

            - task: build-arm
              tags: [arm]
              image: builder-task-image-arm64
              privileged: true
              output_mapping: {image: image-arm}
              params: { TARGET: registry-image-resource, PLATFORM: arm, BUILD_ARG_arch: native }
              file: repository/ci/tasks/build-image.yml

      - in_parallel:
          fail_fast: true
          steps:
            - put: registry-image-resource-arm64
              tags: [arm]
              inputs: [image-arm64]
              get_params: {format: oci}
              params: {image: image-arm64/image.tar}

            - put: registry-image-resource-arm
              tags: [arm]
              inputs: [image-arm]
              get_params: {format: oci}
              params: {image: image-arm/image.tar}


  - name: concourse
    serial: true
    public: true
    plan:
      - in_parallel:
        - get: repository
          passed: [registry-image-resource]
          trigger: true
        - get: registry-image-resource-arm64
          passed: [registry-image-resource]
          tags: [arm]
          trigger: true
        - get: registry-image-resource-arm
          passed: [registry-image-resource]
          tags: [arm]
          trigger: true
        - {get: alpine}
        - {get: builder-task-image}
        - {get: builder-task-image-arm64, tags: [arm]}

      - in_parallel:
          fail_fast: true
          steps:
            - do:
              - task: build-binaries-arm64
                image: builder-task-image
                privileged: true
                output_mapping: {rootfs: binaries-arm64}
                file: repository/ci/tasks/build-binaries.yml
                params: {BUILD_ARG_arch: arm64}

              - task: produce-rc-arm64
                file: repository/ci/tasks/produce-rc.yml
                image: alpine
                input_mapping: 
                  binaries: binaries-arm64
                  registry-image-resource: registry-image-resource-arm64
                output_mapping: {rc: rc-arm64}

              - task: build-rc-image-arm64
                file: repository/ci/tasks/build-rc-image.yml
                image: builder-task-image-arm64
                input_mapping: {rc: rc-arm64}
                output_mapping: {image: image_concourse-arm64}
                params: { BUILD_ARG_arch: arm64 }
                privileged: true
                tags: [arm]

            - do:
              - task: build-binaries-arm
                file: repository/ci/tasks/build-binaries.yml
                image: builder-task-image
                output_mapping: {rootfs: binaries-arm}
                params: {BUILD_ARG_arch: arm}
                privileged: true

              - task: produce-rc-arm
                file: repository/ci/tasks/produce-rc.yml
                image: alpine
                input_mapping: 
                  binaries: binaries-arm
                  registry-image-resource: registry-image-resource-arm
                output_mapping: {rc: rc-arm}

              - task: build-rc-image-arm
                file: repository/ci/tasks/build-rc-image.yml
                image: builder-task-image-arm64
                input_mapping: {rc: rc-arm}
                output_mapping: {image: image_concourse-arm}
                params: { BUILD_ARG_arch: arm }
                privileged: true
                tags: [arm]

      - in_parallel:
          fail_fast: true
          steps:
            - put: concourse-arm-image-arm64
              get_params: {format: oci}
              inputs: [image_concourse-arm64]
              params: {image: image_concourse-arm64/image.tar}
              tags: [arm]

            - put: concourse-arm-image-arm
              get_params: {format: oci}
              inputs: [image_concourse-arm]
              params: {image: image_concourse-arm/image.tar}
              tags: [arm]


resources:
  - name: repository
    type: git
    icon: github-circle
    source: {uri: https://((github-token))@github.com/cirocosta/concourse-arm}

  - name: alpine
    type: registry-image
    icon: docker
    source: {repository: alpine}

  - name: builder-task-image
    type: registry-image
    icon: docker
    source: {repository: cirocosta/builder-task, tag: amd64}

  - name: builder-task-image-arm64
    tags: [arm]
    type: registry-image-arm
    icon: docker
    source:
      repository: cirocosta/builder-task
      tag: arm64
      username: ((docker-user))
      password: ((docker-password))

  - name: builder-task-image-arm
    tags: [arm]
    type: registry-image-arm
    icon: docker
    source:
      repository: cirocosta/builder-task
      tag: arm
      username: ((docker-user))
      password: ((docker-password))

  - name: registry-image-resource-arm64
    tags: [arm]
    type: registry-image-arm
    icon: docker
    source:
      repository: cirocosta/registry-image-resource
      tag: arm64
      platform: {os: linux, architecture: arm64}
      username: ((docker-user))
      password: ((docker-password))

  - name: registry-image-resource-arm
    tags: [arm]
    type: registry-image-arm
    icon: docker
    source:
      repository: cirocosta/registry-image-resource
      tag: arm
      platform: {os: linux, architecture: arm}
      username: ((docker-user))
      password: ((docker-password))

  - name: concourse-arm-image-arm64
    tags: [arm]
    type: registry-image-arm
    icon: docker
    source:
      repository: cirocosta/concourse-arm
      tag: arm64
      platform: {os: linux, architecture: arm64}
      username: ((docker-user))
      password: ((docker-password))

  - name: concourse-arm-image-arm
    tags: [arm]
    type: registry-image-arm
    icon: docker
    source:
      repository: cirocosta/concourse-arm
      tag: arm
      platform: {os: linux, architecture: arm}
      username: ((docker-user))
      password: ((docker-password))


